name: Regions
main: us.camin.regions.Plugin
author: Torrie Fischer <tdfischer@hackerbots.net>
website: http://hackerbots.net/
version: ${version}
api-version: 1.16
softdepend: [dynmap, HolographicDisplays, ProtocolLib]
commands:
    regions:
        description: "List available regions."
        usage: /<command>
    regionop:
        description: "Region admin tools"
        usage: /<command> [args...]
    region:
        description: Interface to the region system
        usage: /<command> [args...]
permissions:
    regions.*:
        default: op
        description: Allows use of all regions permissions
        children:
            regions.create: true
            regions.commands.*: true
            regions.regen.*: true
            regions.bypass.*: true
            regions.give-items.*: true
    regions.regen.*:
        default: op
        description: Allows regeneration of all regions
        children:
            regions.regen: true
            regions.regen.all: true
    regions.use:
        default: true
        description: Use region posts
    regions.create:
        default: true
        description: Create a region with a region item
    regions.setbanner:
        default: true
        description: Allows setting a region post banner
    regions.charge:
        default: true
        description: Allows charging a region post with a charge item
    regions.commands.*:
        default: op
        children:
          regions.commands.remove: true
          regions.commands.regen: true
          regions.commands.regen.all: true
    regions.commands.remove:
        default: op
        description: Remove a region
    regions.commands.regen:
        default: op
        description: Regenerates a region post
    regions.commands.regen.all:
        default: op
        description: Regenerates all region posts, including in unloaded chunks
    regions.bypass.*:
        default: op
        description: Bypasses all region post travel requirements
        children:
          regions.bypass.charges: true
          regions.bypass.discovery: true
    regions.bypass.charges:
        default: op
        description: Allows you to bypass post charge requirements
    regions.bypass.discovery:
        default: op
        description: Allows you to bypass discovery requirements
    regions.give-items.*:
        default: op
        children:
          regions.give-items.compass: true
          regions.give-items.charge: true
          regions.give-items.creator: true
    regions.give-items.compass:
        default: op
    regions.give-items.charge:
        default: op
    regions.give-items.creator:
        default: op
